<?xml version="1.0" encoding="utf-8"?><Database Name="EXPERIMENTS" Class="ExperimentalDataStorageDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=EXPERIMENTS;Integrated Security=True" SettingsObjectName="ExperimentalProcessing.Properties.Settings" SettingsPropertyName="EXPERIMENTSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.RECORDS" Member="RECORDS">
    <Type Name="RECORDS">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DictorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PhraseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="RECORDS_EXPERIMENT" Member="EXPERIMENT" ThisKey="Id" OtherKey="TrainRecordId" Type="EXPERIMENT" />
      <Association Name="RECORDS_EXPERIMENT1" Member="EXPERIMENT1" ThisKey="Id" OtherKey="TestRecordId" Type="EXPERIMENT" />
      <Association Name="PHRASES_RECORDS" Member="PHRASES" ThisKey="PhraseId" OtherKey="Id" Type="PHRASES" IsForeignKey="true" />
      <Association Name="DICTORS_RECORDS" Member="DICTORS" ThisKey="DictorId" OtherKey="Id" Type="DICTORS" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHRASES" Member="PHRASES">
    <Type Name="PHRASES">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="PHRASES_RECORDS" Member="RECORDS" ThisKey="Id" OtherKey="PhraseId" Type="RECORDS" />
    </Type>
  </Table>
  <Table Name="dbo.EXPERIMENT" Member="EXPERIMENT">
    <Type Name="EXPERIMENT">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TrainRecordId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestRecordId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Energy" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="Settings" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TrainDictorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestDictorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="RECORDS_EXPERIMENT" Member="RECORDS" ThisKey="TrainRecordId" OtherKey="Id" Type="RECORDS" IsForeignKey="true" />
      <Association Name="RECORDS_EXPERIMENT1" Member="RECORDS1" ThisKey="TestRecordId" OtherKey="Id" Type="RECORDS" IsForeignKey="true" />
      <Association Name="DICTORS_EXPERIMENT" Member="DICTORS" ThisKey="TrainDictorId" OtherKey="Id" Type="DICTORS" IsForeignKey="true" />
      <Association Name="DICTORS_EXPERIMENT1" Member="DICTORS1" ThisKey="TestDictorId" OtherKey="Id" Type="DICTORS" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DICTORS" Member="DICTORS">
    <Type Name="DICTORS">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="DICTORS_RECORDS" Member="RECORDS" ThisKey="Id" OtherKey="DictorId" Type="RECORDS" />
      <Association Name="DICTORS_EXPERIMENT" Member="EXPERIMENT" ThisKey="Id" OtherKey="TrainDictorId" Type="EXPERIMENT" />
      <Association Name="DICTORS_EXPERIMENT1" Member="EXPERIMENT1" ThisKey="Id" OtherKey="TestDictorId" Type="EXPERIMENT" />
    </Type>
  </Table>
</Database>